services:
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: filter_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8001:8000"
        networks:
            - filter_network
        command: >
            sh -c "php artisan optimize &&
                   php artisan migrate:fresh --seed &&
                   php artisan serve --host=0.0.0.0 --port=8000"

    db:
        image: postgres:13
        container_name: filter_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5433:5432"
        networks:
            - filter_network

volumes:
    postgres_data:
        driver: local

networks:
    filter_network:
        driver: bridge
